name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["Type: Bug :bug:"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Give us a step by step what you did.
      placeholder: Tell us what happened!
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: What did you expect?
      description: This field might be optional depending on the bug you encountered.
      placeholder: Tell us what you wanted to see!
  - type: dropdown
    id: swate-host
    attributes:
      label: Host
      description: Where did you run Swate?
      options:
        - Standalone
        - ARCitect
        - Excel
      default: 0
    validations:
      required: true
  - type: textarea
    id: swate-host-details
    attributes:
      label: Host Details
      description: Please give us more information.
      placeholder: |
        Excel
            * Excel version
            * OS [e.g. Windows 11]
        ARCitect
            * ARCitect version
            * OS [e.g. Windows 11]
        Standalone
            * Browser [e.g. Firefox, Chrome]
    validations:
      required: true
  - type: input
    id: swate-version
    attributes:
      label: Swate version
      description: You can find it at the bottom of the sidebar.
      placeholder: 1.0.0-alpha.01
    validations:
      required: true