name: Feature Request
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: ["Type: Enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch if we need more info?
      placeholder: email, issue, ..
    validations:
      required: false
  - type: textarea
    id: why
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Describe the solution you would like!
      description: A clear and concise description of what you want to happen.
    validations:
      required: true 
  - type: textarea
    id: more-context
    attributes:
      label: Additional context!
      description: Add any other context or screenshots about the feature request here.
  - type: dropdown
    id: swate-host
    attributes:
      label: Host
      description: Where did you run Swate?
      options:
        - Standalone
        - ARCitect
        - Excel
      default: 0
    validations:
      required: true
  - type: textarea
    id: swate-host-details
    attributes:
      label: Host Details
      description: Please give us more information.
      placeholder: |
        Excel
            * Excel version
            * OS [e.g. Windows 11]
        ARCitect
            * ARCitect version
            * OS [e.g. Windows 11]
        Standalone
            * Browser [e.g. Firefox, Chrome]
    validations:
      required: true
